<?php

namespace LGM\AdministrationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OuvrageScientifiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OuvrageScientifiqueRepository extends EntityRepository
{
}
