<?php

namespace LGM\AdministrationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function nombreArticles()
    {
        $qb = $this->createQueryBuilder('a');

        $qb->select('COUNT(a.id) AS nombre')
            ->where('a.actif = true')
            ->orderBy('a.datePublication', 'DESC');

        return $qb->getQuery()->getSingleScalarResult();
    }
}
