lgm_administration_structure:
    resource: "@LGMAdministrationBundle/Resources/config/routing_structure.yml"
    prefix:   /Admin/Structure/
lgm_administration_equipe:
    resource: "@LGMAdministrationBundle/Resources/config/routing_equipe.yml"
    prefix:   /Admin/Equipe/
lgm_administration_projet:
    resource: "@LGMAdministrationBundle/Resources/config/routing_projet.yml"
    prefix:   /Admin/Projet/
lgm_administration_theme:
    resource: "@LGMAdministrationBundle/Resources/config/routing_theme.yml"
    prefix:   /Admin/Theme/
lgm_administration_groupe:
    resource: "@LGMAdministrationBundle/Resources/config/routing_groupe.yml"
    prefix:   /Admin/Groupe/
lgm_administration_article:
    resource: "@LGMAdministrationBundle/Resources/config/routing_article.yml"
    prefix:   /Admin/Article/
lgm_administration_communication:
    resource: "@LGMAdministrationBundle/Resources/config/routing_communication.yml"
    prefix:   /Admin/Communication/
lgm_administration_ouvrageScientifique:
    resource: "@LGMAdministrationBundle/Resources/config/routing_ouvrageScientifique.yml"
    prefix:   /Admin/OuvrageScientifique/
lgm_user_cadre_Equivalant:
    resource: "@LGMUserBundle/Resources/config/routing_cadre_Equivalant.yml"
    prefix:   /Admin/Cadre_Equivalant
lgm_user_doctorant:
    resource: "@LGMUserBundle/Resources/config/routing_doctorant.yml"
    prefix:   /Admin/Doctorant
lgm_user_eleve_Mastere:
    resource: "@LGMUserBundle/Resources/config/routing_eleve_Mastere.yml"
    prefix:   /Admin/Eleve_Mastere
lgm_user_chercheurJunior:
    resource: "@LGMUserBundle/Resources/config/routing_chercheurJunior.yml"
    prefix:   /Admin/Chercheur_Junior
lgm_user_enseignant_Chercheur:
    resource: "@LGMUserBundle/Resources/config/routing_enseignant_Chercheur.yml"
    prefix:   /Admin/Enseignant_Chercheur
lgm_user_resigster:
    resource: "@LGMUserBundle/Resources/config/routing.yml"
    prefix:   /Admin/
lgm_bilan:
    resource: "@LGMAdministrationBundle/Resources/config/routing_bilan.yml"
    prefix:   /Admin/Bilan/
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /Admin/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
lgm_user_admin:
    resource: "@LGMUserBundle/Resources/config/routing_admin.yml"
    prefix:   /Admin/Admin