
index_auteur:
    path:     /index/{token}
    defaults: { _controller: LGMAdministrationBundle:Auteur:index }

new_auteur:
    path:     /new/{token}
    defaults: { _controller: LGMAdministrationBundle:Auteur:new }

edit_auteur:
    path:     /edit/{token}
    defaults: { _controller: LGMAdministrationBundle:Auteur:edit }

delete_auteur:
    path:     /delete/{token}
    defaults: { _controller: LGMAdministrationBundle:Auteur:delete }
