index_communication:
    path:     /index
    defaults: { _controller: LGMAdministrationBundle:Communication:index }
new_communication:
    path:     /new
    defaults: { _controller: LGMAdministrationBundle:Communication:new }
edit_communication:
    path:     /edit/{token}
    defaults: { _controller: LGMAdministrationBundle:Communication:edit }
delete_communication:
    path:     /delete/{token}
    defaults: { _controller: LGMAdministrationBundle:Communication:delete }
