index_theme:
    path:     /index
    defaults: { _controller: LGMAdministrationBundle:Theme:index }
new_theme:
    path:     /new
    defaults: { _controller: LGMAdministrationBundle:Theme:new }
edit_theme:
    path:     /edit/{token}
    defaults: { _controller: LGMAdministrationBundle:Theme:edit }
delete_theme:
    path:     /delete/{token}
    defaults: { _controller: LGMAdministrationBundle:Theme:delete }
