index_structure:
    path:     /index
    defaults: { _controller: LGMAdministrationBundle:Structure:index }
new_structure:
    path:     /new
    defaults: { _controller: LGMAdministrationBundle:Structure:new }
edit_structure:
    path:     /edit/{token}
    defaults: { _controller: LGMAdministrationBundle:Structure:edit }
delete_structure:
    path:     /delete/{token}
    defaults: { _controller: LGMAdministrationBundle:Structure:delete }
