<?php

namespace LGM\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Cadre_EquivalantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cadre_EquivalantRepository extends EntityRepository
{
}
