<?php

namespace LGM\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Chercheur_JuniorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Chercheur_JuniorRepository extends EntityRepository
{
}
