<?php

namespace LGM\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Eleve_MastereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Eleve_MastereRepository extends EntityRepository
{
}
