fos_enseignant_chercheur_registration:
    pattern:  /inscription/Enseignant_Chercheur
    defaults: { _controller: LGMUserBundle:RegistrationEnseignant_Chercheur:register }

fos_chercheur_junior_registration:
    pattern:  /inscription/Chercheur_Junior
    defaults: { _controller: LGMUserBundle:RegistrationChercheur_Junior:register }
  
fos_admin_registration:
    pattern:  /inscription/Admin
    defaults: { _controller: LGMUserBundle:RegistrationAdmin:register }

user_bienvenue:
    pattern:  /Bienvenue
    defaults: { _controller: LGMUserBundle:Default:index }
